config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"
  resources :friendships
  resources :friend_requests
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :posts do
    resources :comments, except: :show
  end
  resources :groups do
    get :members
  end
  resources :memberships do
    put :approve, to: 'memberships#approve'
    put :cancel
    put :decline
    put :leave
    put :remove
  end
  get 'search_entries/index', as: 'search'
  post 'members/:group_id', as: :invite, to: 'groups#invite'
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: :destroy

  def index
    @friends = current_user.friends
  end

  def destroy
    current_user.friends.destroy(@friend)
    flash[:notice] = "User #{@friend.username} has been removed from friend lists"
    redirect_to friends_path
  end

  private

  def set_friend
    @friend = current_user.friends.find(params[:id])
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/index.html.erb
<div class="container">
  <h1>List of Friends</h1>
  <table>
    <thead>
    <th>Email</th>
    <th>Username</th>
    <th>Action</th>
    </thead>
    <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td><%= friend.email %></td>
        <td><%= friend.username %></td>
        <td><%= button_to 'Remove Friend', friend_path(friend), method: :delete, data: { turbo_confirm: "Are you sure you want to remove #{friend.username} as friend?" } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>