config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"
  resources :friendships
  resources :friend_requests
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :posts do
    resources :comments, except: :show
  end
  resources :groups do
    get :members
  end
  resources :memberships do
    put :approve, to: 'memberships#approve'
    put :cancel
    put :decline
    put :leave
    put :remove
  end
  get 'search_entries/index', as: 'search'
  post 'members/:group_id', as: :invite, to: 'groups#invite'
end

app/models/group.rb
class Group < ApplicationRecord
  include Searchable
  after_commit :create_search_entry, on: :create
  after_commit :update_search_entry, on: :update
  after_commit :destroy_search_entry, on: :destroy
  validates :name, :privacy, :description, :banner, presence: true
  belongs_to :user
  has_many :memberships
  mount_uploader :banner, ImageUploader
  enum privacy: { community: 0, hidden: 1 }

  private

  def create_search_entry
    SearchEntry.create(image: self.banner, name: self.name, body: self.description, searchable: self)
  end

  def update_search_entry
    self.search_entry.update(image: self.banner, name: self.name, body: self.description) if self.search_entry.present?
  end

  def destroy_search_entry
    self.search_entry.destroy if self.search_entry.present?
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  def index
    group_ids = current_user.memberships.where.not(state: [:decline, :leave]).pluck(:group_id)
    @groups = current_user.groups.where.not(id: group_ids)
    @groups = current_user.groups.where(user: current_user)
    @joined_groups = Membership.where(user: current_user).where(state: :approved).where.not(role: :admin).includes(:user, :group)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user = current_user
    if @group.save
      @group_member = current_user.memberships.new(user_id: current_user, group: @group, role: :admin, is_owner: true, state: :approved)
      @group_member.save
      flash[:notice] = "Group has been successfully created"
      redirect_to groups_path
    else
      render :new
    end
  end

  def show
    @members = Membership.approved.where(group: @group).count
  end

  def edit
    authorize @group, :edit?, policy_class: GroupPolicy
  end

  def update
    authorize @group, :update?, policy_class: GroupPolicy
    if @group.update(group_params)
      flash[:notice] = "Group has been edited"
      redirect_to groups_path
    else
      render :edit
    end
  end

  def destroy
    authorize @group, :destroy?, policy_class: GroupPolicy
    @group.destroy
    flash[:notice] = "Group has been deleted"
    redirect_to groups_path
  end

  def members
    @join_groups = Membership.includes(:user, :group).where(group_id: set_join_group)
    @current_members = @join_groups.where.not(state: :requesting)
    # @sent_requests = @join_groups.where(user: current_user).requesting
    @received_requests = @join_groups.requesting
    # @can_invite = current_user.memberships.where(group: @group).where(can_invite: 1).present? == true
    @user_friends = current_user.friends.where.not(id: @group.memberships.where(state: :approved).pluck(:user_id))
  end

  def invite
    invite_friend = Membership.where(group_id: params[:group_id]).where(user: params[:user_id]).blank?
    if invite_friend
      @join_group = Membership.new(group_id: params[:group_id], user_id: params[:user_id], role: :normal, state: :approved)
      if @join_group.save
        redirect_to groups_path
        flash[:notice] = "Added to group!"
      else
        flash[:alert] = @join_group.errors.full_messages.join(", ")
        redirect_to groups_path
      end
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :banner, :description, :privacy, :can_invite)
  end

  def set_group
    @group = Group.find(params[:id])
  end

  def set_join_group
    @group = Group.find(params[:group_id])
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<div class="offcanvas offcanvas-start show text-bg-dark" tabindex="-1" id="offcanvasDark" aria-labelledby="offcanvasDarkLabel">
  <%= form_with model: @group, url: group_path, data: { turbo: false } do |form| %>
    <div class="offcanvas-header">
      <%= link_to '', groups_path, class: "btn-close btn-close-white" %>
    </div>
    <div class="offcanvas-body">
      <small class="text-muted d-block"><%= link_to 'Groups', groups_path, class: "text-muted nav-link d-inline" %>
        › Create group</small>
      <h5 class="offcanvas-title" id="offcanvasDarkLabel">Edit Group</h5>
    </div>
    <div class="offcanvas-body">
      <div class="mb-2">
        <%= form.label :cover_photo %>
        <%= form.file_field :banner, class: "form-control bg-dark text-white", style: "border-color: #666666" %>
      </div>
      <div class="mb-2">
        <% invalid = @group.errors.include?(:name) %>
        <%= form.text_field :name, class: "form-control bg-dark text-white #{'is-invalid' if invalid}", placeholder: "Enter Name", style: "border-color: #666666" %>
        <% if invalid %>
          <small class="invalid-feedback d-block">
            <% @group.errors.full_messages_for(:name).each do |error_message| %>
              <%= error_message %>.
            <% end %>
          </small>
        <% end %>
      </div>
      <div class="mb-2">
        <%= form.select :privacy, Group.privacies.keys.map { |w| [w.humanize, w] }, { prompt: 'Choose privacy' }, class: "form-control form-select bg-dark text-white", style: "border-color: #666666" %>
      </div>
      <div class="mb-2">
        <% invalid = @group.errors.include?(:description) %>
        <%= form.text_field :description, class: "form-control bg-dark text-white  #{'is-invalid' if invalid}", placeholder: "Enter Description", style: "border-color: #666666" %>
        <% if invalid %>
          <small class="invalid-feedback d-block">
            <% @group.errors.full_messages_for(:description).each do |error_message| %>
              <%= error_message %>.
            <% end %>
          </small>
        <% end %>
      </div>
      <div class="mb-2">
        <% invalid = @group.errors.include?(:can_invite) %>
        <%= form.label 'Invite Permission', class: "d-block" %>
        <%= form.select :can_invite, [['Allow invite', true], ['Disable invite', false]], { prompt: 'Please Select' }, class: "form-control form-select bg-dark text-white #{'is invalid' if invalid}", style: "border-color: #666666" %>
        <% if invalid %>
          <small class="invalid-feedback d-block">
            <% @group.errors.full_messages_for(:can_invite).each do |error_message| %>
              <%= error_message %>.
            <% end %>
          </small>
        <% end %>
      </div>
    </div>
    <div class="offcanvas-body">
      <%= form.submit class: "w-100 btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/groups/index.html.erb
<div class="container">
  <div class="mb-3 text-end">
    <%= link_to 'Create new group', new_group_path, class: "btn btn-primary bi bi-plus-lg text-primary", style: "background-color: rgba(45,136,255, 0.2); border: 0" %>
  </div>
  <% @groups.each do |group| %>
    <div class="card bg-dark mb-3">
      <div class="card-body">
        <div class="d-flex flex-row gap-2">
          <div class=""><%= image_tag group.banner.url, height: 70, width: 70, class: "rounded" if group.banner? %>
          </div>
          <div class="flex-column">
            <p><%= group.name %></p>
            <p><%= group.description %></p>
            <p><%= group.privacy.humanize %></p>
          </div>
        </div>
        <div class="d-flex flex-row gap-2">
          <div class="flex-grow-1">
            <%= link_to 'View Group', group_path(group), class: "btn btn-primary text-primary w-100", style: "background-color: rgba(45,136,255, 0.2); border: 0" if current_user.memberships.where(group: group).present? %>
            <%= button_to 'Join', { action: :create, controller: 'memberships', group_id: group }, data: { turbo_confirm: "Are you sure, you want to join?", turbo: false }, method: :post, class: 'btn btn-primary text-primary w-100 mt-2', style: "background-color: rgba(45,136,255, 0.2); border: 0" if current_user.memberships.where(group: group).blank? %>
          </div>
          <% if policy(group).edit? && policy(group).destroy? %>
            <div class="dropdown ">
              <button type="button" data-bs-toggle="dropdown" aria-expanded="false" class="btn btn-secondary" style="background-color: rgba(255,255,255, 0.1); border: 0">
                <i class="bi bi-three-dots text-white"></i>
              </button>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit", edit_group_path(group), class: "dropdown-item bi bi-pencil" %></li>
                <li><%= button_to "Delete", group_path(group), method: :delete, data: { turbo_confirm: "Are you sure you want to delete this group?" }, class: "dropdown-item bi bi-trash3" %></li>
              </ul>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

  <% @joined_groups&.each do |joined| %>
    <div class="card bg-dark mb-3">
      <div class="card-body">
        <div class="d-flex flex-row gap-2">
          <div class=""><%= image_tag joined.group.banner.url, height: 70, width: 70, class: "rounded" if joined.group.banner? %>
          </div>
          <div class="flex-column">joined
            <p><%= joined.group.user.email %></p>
            <p><%= joined.group.description %></p>
            <p><%= joined.group.privacy.humanize %></p>
          </div>
        </div>
        <div class="d-flex flex-row gap-2">
          <div class="flex-grow-1">
            <%= link_to 'View Group', group_path(joined.group), class: "btn btn-primary text-primary w-100", style: "background-color: rgba(45,136,255, 0.2); border: 0" if current_user.memberships.where(group: joined.group).present? %>
            <%= button_to 'Join', { action: :create, controller: 'memberships', group_id: joined.group_id }, data: { turbo_confirm: "Are you sure, you want to join?", turbo: false }, method: :post, class: 'btn btn-primary text-primary w-100 mt-2', style: "background-color: rgba(45,136,255, 0.2); border: 0" if current_user.memberships.where(group: joined.group).blank? %>
          </div>
          <% if policy(joined.group).edit? && policy(joined.group).destroy? %>

            <div class="dropdown ">
              <button type="button" data-bs-toggle="dropdown" aria-expanded="false" class="btn btn-secondary" style="background-color: rgba(255,255,255, 0.1); border: 0">
                <i class="bi bi-three-dots text-white"></i>
              </button>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit", edit_group_path(joined), class: "dropdown-item bi bi-pencil" %></li>
                <li><%= button_to "Delete", group_path(joined), method: :delete, data: { turbo_confirm: "Are you sure you want to delete this group?" }, class: "dropdown-item bi bi-trash3" %></li>
              </ul>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/groups/members.html.erb
<div class="container">
  <div class="d-flex justify-content-center">
    <div class="card bg-dark flex-grow-1" style="max-width: 40rem">
      <div class="card-header text-center"><h2>Member List</h2></div>
      <% @current_members.each do |current_members| %>
        <div class="card-body p-3">
          <div class="d-flex gap-2">
            <%= image_tag 'erwin.jpeg', height: 60, width: 60, class: "rounded-circle" %>
            <div class="flex-column ">
              <span class="d-block"><%= current_members.user.username %></span>
              <span class="d-block"><%= current_members.role.humanize if current_members.role == "admin" %></span>
              <small class="text-muted">Joined date: <%= current_members.created_at.strftime('%B %d, %Y') %></small>
            </div>
            <div class="dropdown">
              <button type="button" data-bs-toggle="dropdown" aria-expanded="false" class="btn btn-dark" style="border: 0; background-color: #666666; opacity: 40%; color: white">
                <i class="bi bi-three-dots text-white"></i>
              </button>
              <ul class="dropdown-menu">
                <li><%= button_to "Add as admin", '#', method: :delete, data: { turbo_confirm: "Are you sure you want to add #{current_members.user.username} as admin?" }, class: "dropdown-item" %></li>
                <li><%= button_to "Add as moderator", '#', method: :delete, data: { turbo_confirm: "Are you sure you want to add #{current_members.user.username} as moderator?" }, class: "dropdown-item" %></li>
                <li><%= button_to "Remove member", '#', method: :delete, data: { turbo_confirm: "Are you sure you want to remove #{current_members.user.username} as member?" }, class: "dropdown-item" %></li>
              </ul>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="d-flex justify-content-center mt-5">
    <div class="card bg-dark flex-grow-1" style="max-width: 40rem">
      <div class="card bg-dark flex-grow-1" style="max-width: 40rem">
        <div class="card-header text-center"><h2>Received request</h2></div>
        <% @received_requests.each do |received_request| %>
          <% if current_user == received_request.group.user %>
            <div class="card-body p-3">
              <div class="d-flex gap-2">
                <%= image_tag received_request.group.banner.url, height: 60, width: 60, class: "rounded-circle" if received_request.group.banner.present? %>
                <div class="flex-column ">
                  <h6>Sent by <%= received_request.user.email %></h6>
                </div>
                <%= button_to "Approve", membership_approve_path(received_request), method: :put, class: 'btn btn-outline-primary btn-sm', data: { confirm: "Are you sure, you want to approve?" } if received_request.may_approve? %>
                <%= button_to "Decline", membership_decline_path(received_request), method: :put, class: 'btn btn-outline-danger btn-sm', data: { confirm: "Are you sure, you want to decline?" }  if received_request.may_decline? %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <% if @group.can_invite == true %>
    <div class="d-flex justify-content-center mt-5">
      <div class="card bg-dark flex-grow-1" style="max-width: 40rem">
        <div class="card bg-dark flex-grow-1" style="max-width: 40rem">
          <div class="card-header text-center"><h2>Invite friends</h2></div>
          <% @user_friends.each do |user_friend| %>
            <div class="card-body p-3">
              <div class="d-flex gap-2">
                <%= image_tag 'erwin.jpeg', height: 60, width: 60, class: "rounded-circle"%>
                <div class="flex-column ">
                  <%= user_friend.username %>
                </div>
                <%= button_to 'Invite', { action: :invite, controller: 'groups', group_id: @group.id, user_id: user_friend.id }, data: { turbo_confirm: "Are you sure, you want to #{user_friend.username}?", turbo: false }, method: :post, class: 'btn btn-primary text-primary w-100 mt-2', style: "background-color: rgba(45,136,255, 0.2); border: 0" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/groups/new.html.erb
<div class="offcanvas offcanvas-start show text-bg-dark" tabindex="-1" id="offcanvasDark" aria-labelledby="offcanvasDarkLabel">
  <%= form_with model: @group, url: groups_path, data: { turbo: false } do |form| %>
    <div class="offcanvas-header">
      <%= link_to '', groups_path, class: "btn-close btn-close-white" %>
    </div>
    <div class="offcanvas-body">
      <small class="text-muted d-block"><%= link_to 'Groups', groups_path, class: "text-muted nav-link d-inline" %>
        › Create group</small>
      <h5 class="offcanvas-title" id="offcanvasDarkLabel">Create Group</h5>
    </div>
    <div class="offcanvas-body">
      <div class="mb-2">
        <%= form.label :cover_photo %>
        <%= form.file_field :banner, class: "form-control bg-dark text-white", style: "border-color: #666666" %>
      </div>
      <div class="mb-2">
        <% invalid = @group.errors.include?(:name) %>
        <%= form.text_field :name, class: "form-control bg-dark text-white #{'is-invalid' if invalid}", placeholder: "Enter Name", style: "border-color: #666666" %>
        <% if invalid %>
          <small class="invalid-feedback d-block">
            <% @group.errors.full_messages_for(:name).each do |error_message| %>
              <%= error_message %>.
            <% end %>
          </small>
        <% end %>
      </div>
      <div class="mb-2">
        <%= form.select :privacy, Group.privacies.keys.map { |w| [w.humanize, w] }, { prompt: 'Choose privacy' }, class: "form-control form-select bg-dark text-white", style: "border-color: #666666" %>
      </div>
      <div class="mb-2">
        <% invalid = @group.errors.include?(:description) %>
        <%= form.text_field :description, class: "form-control bg-dark text-white  #{'is-invalid' if invalid}", placeholder: "Enter Description", style: "border-color: #666666" %>
        <% if invalid %>
          <small class="invalid-feedback d-block">
            <% @group.errors.full_messages_for(:description).each do |error_message| %>
              <%= error_message %>.
            <% end %>
          </small>
        <% end %>
      </div>
      <div class="mb-2">
        <% invalid = @group.errors.include?(:can_invite) %>
        <%= form.label 'Invite Permission', class: "d-block" %>
        <%= form.select :can_invite, [['Allow invite', true], ['Disable invite', false]], { prompt: 'Please select' }, class: "form-control form-select bg-dark text-white #{'is invalid' if invalid}", style: "border-color: #666666" %>
        <% if invalid %>
          <small class="invalid-feedback d-block">
            <% @group.errors.full_messages_for(:can_invite).each do |error_message| %>
              <%= error_message %>.
            <% end %>
          </small>
        <% end %>
      </div>
    </div>
    <div class="offcanvas-body">
      <%= form.submit class: "w-100 btn btn-primary" %>
    </div>
  <% end %>
</div>