config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"
  resources :friendships
  resources :friend_requests
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :posts do
    resources :comments, except: :show
  end
  resources :groups do
    get :members
  end
  resources :memberships do
    put :approve, to: 'memberships#approve'
    put :cancel
    put :decline
    put :leave
    put :remove
  end
  get 'search_entries/index', as: 'search'
  post 'members/:group_id', as: :invite, to: 'groups#invite'
end

app/models/post.rb
class Post < ApplicationRecord
  include Searchable
  after_commit :create_search_entry, on: :create
  after_commit :update_search_entry, on: :update
  after_commit :destroy_search_entry, on: :destroy
  validates :content, presence: true
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :comments
  enum audience: { post_public: 0, only_friend: 1, post_private: 2 }

  private

  def create_search_entry
    SearchEntry.create(image: self.image, name: self.user.username, body: self.content, searchable: self)
  end

  def update_search_entry
    self.search_entry.update(image: self.image, name: self.user.username, body: self.content) if self.search_entry.present?
  end

  def destroy_search_entry
    self.search_entry.destroy if self.search_entry.present?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.includes(:user).order(id: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if Rails.env.development?
      @post.location = Net::HTTP.get(URI.parse('http://checkip.amazonaws.com/')).squish
      @post.location = Geocoder.search(@post.location).first.city
    else
      @post.location = request.remote_ip
    end
    if @post.save
      flash[:notice] = "Post was successfully saved"
      redirect_to posts_path
    else
      render :new
    end
  end

  def show; end

  def edit
    authorize @post, :edit?, policy_class: PostPolicy
  end

  def update
    authorize @post, :update?, policy_class: PostPolicy
    if @post.update(post_params)
      flash[:notice] = "Post successfully updated"
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    authorize @post, :destroy?, policy_class: PostPolicy
    @post.destroy
    flash[:notice] = "Post successfully deleted"
    redirect_to posts_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:image, :content, :audience, :location)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment_index.html.erb
<article>
  <% @post.comments.order(id: :desc).each do |comment| %>
    <div style="display: flex; flex-direction: row; align-items: center">
      <div>
        <small class="text-muted d-block"><%= comment.user.username %></small>
        <small class="text-muted d-block"><%= time_ago_in_words(comment.created_at) %> ago</small>
        <p class="text-black"><%= comment.content %></p>
      </div>
      <div style="display: flex; flex-direction: row;">
        <%= link_to 'Edit', edit_post_comment_path(@post, comment), class: "btn btn-outline-success m-2" if policy(comment).edit? %>
        <%= button_to 'Delete', post_comment_path(@post, comment), method: :delete, :onclick => "return confirm('Are you sure you want to delete?')", class: "btn btn-outline-danger m-2" if policy(comment).destroy? %>
      </div>
    </div>
    <hr class="text-muted ">
  <% end %>
</article>

app/views/posts/_form.html.erb
<%= form_with model: post, url: path do |form| %>
  <div class="d-flex align-items-center gap-2">
    <%= image_tag 'erwin.jpeg', alt: "Profile", height: 40, width: 40, class: "rounded-circle" %>
    <div class="flex-column">
      <small style="display: block"><%= current_user.username %></small>
      <%= form.select :audience, Post.audiences.keys.map { |key| [key.humanize, key] }, { prompt: 'Choose Status' }, class: "form-control-sm form-select-sm mb-2 bg-dark text-white", style: "max-width: 9rem;" %>
    </div>
  </div>
  <div class="mt-4 mb-2">
    <% invalid = post.errors.include?(:content) %>
    <%= form.text_field :content, class: "form-control text-white #{'is-invalid' if invalid}", style:"outline: none;
              padding: 5px;
              border: 0px;
              box-sizing: unset;
              background-color: transparent;", placeholder: "What's on your mind #{current_user.username}?" %>
    <% if invalid %>
      <div class="invalid-feedback d-block">
        <% post.errors.full_messages_for(:content).each do |error_message| %>
          <%= error_message %>.
        <% end %>
      </div>
    <% end %>
  </div>
  <%= form.file_field :image, class: "form-control mb-2" %>
  <%= form.submit class: "btn btn-primary w-100 mt-4" %>
<% end %>

app/views/posts/_form_modal.html.erb
<%= turbo_frame_tag :remote_modal, target: :_top do %>
  <div class="modal" id="staticBackdrop" data-controller="modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content bg-dark" style="background-color: #666666;">
        <div class="modal-header text-center">
          <h1 class="modal-title fs-5 text-black" id="staticBackdropLabel"></h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= render partial: 'form', locals: { post: @post, path: path } %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%= render partial: 'form_modal', locals: { post: @post, path: post_path } %>

app/views/posts/edit.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render partial: 'posts/form_modal', locals: { post: @post, path: post_path } %>
<% end %>

app/views/posts/index.html.erb
<div class="container text-white">
  <div class="card rounded bg-dark">
    <div class="card-body">
      <div class="d-flex gap-2">
        <%= image_tag 'erwin.jpeg', alt: "Profile", height: 40, width: 40, class: "rounded-circle" %>
        <%= link_to "What's on your mind, #{current_user.username}?", new_post_path, "data-controller": "turbo", class: "btn btn-dark w-100 text-start", style: "background-color: #666666; border-radius: 20px; opacity: 40%" %>
      </div>
    </div>
    <div class="card-footer">

    </div>
  </div>

  <% @posts.each do |post| %>
    <div class="card bg-dark mt-3">
      <div class="card-header">
        <div class="d-flex align-items-center gap-2">
          <%= image_tag 'erwin.jpeg', alt: "Profile", height: 40, width: 40, class: "rounded-circle" %>
          <div class="flex-column flex-grow-1">
            <p style="margin: 0"><%= post.user.username %></p>
            <small class="text-muted"><%= time_ago_in_words(post.created_at) %> <span class="text-white">&middot;</span>
              <% if post.post_public? %>
                <i class="bi bi-globe-asia-australia"></i>
              <% end %>
              <% if post.only_friend? %>
                <i class="bi bi-people-fill"></i>
              <% end %>
              <% if post.post_private? %>
                <i class="bi bi-lock-fill"></i>
              <% end %>
              <% if post.location? %>
                <span class="text-white">&middot;</span>
                <%= post.location %>
              <% end %>
            </small>

          </div>
          <div class="dropdown">
            <button style="outline: none;
              padding: 5px;
              border: 0px;
              box-sizing: unset;
              background-color: transparent;" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi bi-three-dots text-white"></i>
            </button>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit", edit_post_path(post), "data-controller": "turbo", class: "dropdown-item bi bi-pencil" if policy(post).edit? %></li>
              <li><%= link_to "Show", post_path(post), class: "dropdown-item bi bi-eye" %></li>
              <li><%= button_to "Delete", post_path(post), method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "dropdown-item bi bi-trash3" if policy(post).destroy? %></li>
            </ul>
          </div>
        </div>

      </div>
      <div class="card-body">
        <p><%= post.content %></p>
        <%= image_tag post.image.url, class: "rounded w-100", height: 400 if post.image? %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= render partial: 'form_modal', locals: { post: @post, path: posts_path } %>

app/views/posts/new.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render partial: 'posts/form_modal', locals: { post: @post, path: posts_path } %>
<% end %>

app/views/posts/show.html.erb
<div class="container">
  <div class="card bg-dark">
    <div class="card-header">
      <div class="d-flex align-items-center gap-2">
        <%= image_tag 'erwin.jpeg', alt: "Profile", height: 40, width: 40, class: "rounded-circle" %>
        <div class="flex-column flex-grow-1">
          <p style="margin: 0"><%= current_user.username %></p>
          <small class="text-muted"><%= time_ago_in_words(@post.created_at) %> <span class="text-white">&middot;</span>
            <% if @post.post_public? %>
              <i class="bi bi-globe-asia-australia"></i>
            <% end %>
            <% if @post.only_friend? %>
              <i class="bi bi-people-fill"></i>
            <% end %>
            <% if @post.post_private? %>
              <i class="bi bi-lock-fill"></i>
            <% end %>
          </small>
        </div>
      </div>

    </div>
    <div class="card-body">
      <p><%= @post.content %></p>
    </div>
    <div class="card-footer">
      <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
        Show comments
      </a></strong></p>
      <div class="collapse.show mb-5" id="collapseExample">
        <div class="card card-body">
          <%= render 'posts/comment_index' %>
          <%= render partial: 'comments/form', locals: { comment: @post.comments.new, path: post_comments_path(@post) } %>
        </div>
      </div>
    </div>
  </div>
</div>