config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"
  resources :friendships
  resources :friend_requests
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :posts do
    resources :comments, except: :show
  end
  resources :groups do
    get :members
  end
  resources :memberships do
    put :approve, to: 'memberships#approve'
    put :cancel
    put :decline
    put :leave
    put :remove
  end
  get 'search_entries/index', as: 'search'
  post 'members/:group_id', as: :invite, to: 'groups#invite'
end

app/views/layouts/_header_form.html.erb
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <div class="container">
    <div class="text-white d-flex">
    <%= link_to (image_tag "koda.png", height: 50, width: 50, class: "rounded-circle"), posts_path, class: "navbar-brand fs-6" %>
    <div class="navbar text-white"  >
      <%= form_with url: :search, method: :get do |form| %>
      <%= form.text_field :query, class: "btn btn-dark w-100 text-start bi bi-search", style: "background-color: #666666; border-radius: 20px; opacity: 40%; color: white", placeholder: "Search" %>
    <% end %>
    </div>
    </div>

    <ul class="nav nav-pills ">
      <li class="nav-item dropdown ms-auto">
        <%= link_to 'Find Friends', friend_requests_path, class: "bi bi-person-fill-add nav-link text-white" %>
      </li>
      <li class="nav-item dropdown ms-auto">
        <%= link_to 'Friends', friendships_path, class: "bi bi-people-fill nav-link text-white" %>
      </li>
      <li class="nav-item dropdown ms-auto">
        <%= link_to 'Groups', groups_path, class: "nav-link text-white" %>
      </li>
      <li class="nav-item dropdown ms-auto">
        <a href="#" class="nav-link text-white" data-bs-toggle="dropdown"><%= image_tag "erwin.jpeg", height: 40, width: 40, class: "rounded-circle" %></a>
        <div class="dropdown-menu dropdown-menu-end">
          <% if user_signed_in? %>
            <a href="#" class="dropdown-item" data-bs-toggle="dropdown">Profile</a>
            <a href="#" class="dropdown-item">Settings</a>
            <div class="dropdown-divider"></div>
            <%= button_to "Log Out", destroy_user_session_path, { onclick: "return confirm('Are you sure you want to delete?')", method: :delete, class: "dropdown-item" } %>
          <% else %>
            <%= link_to "Login", new_user_session_path, class: "dropdown-item" %>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body style="background-color: #121212" class="text-white">
  <%= render 'layouts/header_form' %>
  <span class="notice text-success"><%= notice %></span>
  <span class="alert text-danger"><%= alert %></span>
  <%= yield %>
  <%= turbo_frame_tag "remote_modal" %>
  </body>
</html>